### ISSUE TITLE
Informace o vadnem telefonim cisle nezmizi i kdyz se pokousim o opravu

### ISSUE THREAD

**Issue by krakorj** [covid19cz/bt-tracing-android#15]
**Testuju na**

Samsung SM-A202F

Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.widerwille.afterglow

**Jak jsem postupoval**

Nainstaloval jsem - ok
Spustil jsem - ok
Aniz bych zadaval svoje tel cislo, stiskl jsem tlacitko registrovat --> objevilo se varovani
Zadaval jsem telefoni cislo --> varovani nezmizelo

**Jak bych si to predstavoval?**

Varovani zmizi jakmile uzivatel zacne opravovat nebo zadavat nove cislo

**Comment by davidvavra** [comment]
Prosím bugy do Trella, ne sem
