### ISSUE TITLE
Pridat funkci na odstraneni telefonniho cisla ze sluzby

### ISSUE THREAD

**Issue by krakorj** [covid19cz/bt-tracing-android#16]
**Testuju na**

Samsung SM-A202F

Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.widerwille.afterglow

**Co bych chtel**

Chtel bych mit moznost deaktivovat svoje telefonni cislo ze sluzby. 

**Dodatek**

Je neprijemne, ze se ted moje cislo nekde vali a ja nevim koho kontaktovat aby moje cislo ze seznamu odstanil. Zavani mi to problemy s GDPR. Bude to resit hodne uzivatelu az se vsichni vyleci a nebude jiz aplikace potreba ... kez by to bylo brzy ;)

**Comment by davidvavra** [comment]
Prosím bugy do Trella, ne sem
