### ISSUE TITLE
UX updates

### ISSUE THREAD

**Issue by krakorj** [covid19cz/bt-tracing-android#17]
**Testuju na**

Samsung SM-A202F

Android Studio 3.6.1
Build #AI-192.7142.36.36.6241897, built on February 27, 2020
Runtime version: 1.8.0_212-release-1586-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1246M
Cores: 4
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: com.widerwille.afterglow

Verze aplikace 0.6.92

**V bodech**

* Registracni formular se mi libi az na bug #15
* Po registraci a opetovnem prihlaseni bych se chtel dostat na rozcestnik, ktery:
  * Bude mit minimalne v titulku informaci ze jsem v aplikaci `eRouska`, lepe bude mit hlavicku s logem (ktere se Vam povedlo ;))
  * Ukaze mi  stav - Sledovani je aktivni na mem telefonnim cisle XYZ, pri vysilacim vykonu XYZ
  * Da mi moznost sluzbu aktivovat/deaktivovat
  * Da mi moznost se podivat do databaze/Exportovat
  * Ukaze mi dodatecne informace 
    * Zopakuje telefonni cislo 1212
    * ... 
  * Da mi moznost se odhlasit ze sluzby
  * Bonus
    * Ukaze mi pocet ulovenych zarizeni - gamifikace?
    * Ukaze mi pocet zarizeni v okoli prave ted
    * Ukaze mi kolik lidi si jiz aplikaci nainstalovalo abych v tom nebyl sam
    * Ukaze mi stav COVID-19 v CR
    * ...

**Comment by davidvavra** [comment]
Prosím bugy do Trella, ne sem
